//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.GammaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GammaService.IPrinterService")]
    public interface IPrinterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinterService/PrintPallet", ReplyAction="http://tempuri.org/IPrinterService/PrintPalletResponse")]
        bool PrintPallet(System.Guid productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinterService/ActivateProductionTask", ReplyAction="http://tempuri.org/IPrinterService/ActivateProductionTaskResponse")]
        bool ActivateProductionTask(System.Guid productionTaskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrinterServiceChannel : Gamma.GammaService.IPrinterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrinterServiceClient : System.ServiceModel.ClientBase<Gamma.GammaService.IPrinterService>, Gamma.GammaService.IPrinterService {
        
        public PrinterServiceClient() {
        }
        
        public PrinterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrinterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PrintPallet(System.Guid productId) {
            return base.Channel.PrintPallet(productId);
        }
        
        public bool ActivateProductionTask(System.Guid productionTaskId) {
            return base.Channel.ActivateProductionTask(productionTaskId);
        }
    }
}
