//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveProductionTasks
    {
        public int PlaceID { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
    
        public virtual ProductionTasks ProductionTasks { get; set; }
        public virtual Places Places { get; set; }
    }
}
