//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveProductionTasks
    {
        public int PlaceID { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
    
        public virtual ProductionTasks ProductionTasks { get; set; }
        public virtual Places Places { get; set; }
    }
}
