//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branches()
        {
            this.Persons = new HashSet<Persons>();
            this.Places = new HashSet<Places>();
        }
    
        public int BranchID { get; set; }
        public int EnterpriseID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phones { get; set; }
        public string WebInfo { get; set; }
        public string QualityContacts { get; set; }
        public Nullable<System.Guid> C1CSubdivisionID { get; set; }
        public Nullable<System.DateTime> LastAvailableJobTime { get; set; }
        public string AddressEng { get; set; }
        public string PhonesEng { get; set; }
        public string DocPrefix { get; set; }
    
        public virtual Enterprises Enterprises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persons> Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Places> Places { get; set; }
    }
}
