//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CContractors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C1CContractors()
        {
            this.C1CDocShipmentOrder = new HashSet<C1CDocShipmentOrder>();
            this.C1CDocShipmentOrder1 = new HashSet<C1CDocShipmentOrder>();
            this.C1CDocShipmentOrder2 = new HashSet<C1CDocShipmentOrder>();
            this.ProductionTaskBatches = new HashSet<ProductionTaskBatches>();
        }
    
        public System.Guid C1CContractorID { get; set; }
        public bool Marked { get; set; }
        public bool Folder { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string C1CCode { get; set; }
        public string Description { get; set; }
        public string FullDescription { get; set; }
        public Nullable<bool> IsBuyer { get; set; }
        public Nullable<bool> IsSeller { get; set; }
        public Nullable<bool> IsNonresident { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocShipmentOrder> C1CDocShipmentOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocShipmentOrder> C1CDocShipmentOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocShipmentOrder> C1CDocShipmentOrder2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionTaskBatches> ProductionTaskBatches { get; set; }
    }
}
