//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CDocShipmentOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C1CDocShipmentOrder()
        {
            this.C1CDocShipmentOrderGoods = new HashSet<C1CDocShipmentOrderGoods>();
        }
    
        public System.Guid C1CDocShipmentOrderID { get; set; }
        public bool Marked { get; set; }
        public bool Posted { get; set; }
        public Nullable<System.DateTime> C1CDate { get; set; }
        public string C1CNumber { get; set; }
        public Nullable<System.Guid> C1CContractorID { get; set; }
        public Nullable<System.Guid> C1CConsigneeID { get; set; }
        public Nullable<System.Guid> C1CShipperID { get; set; }
        public Nullable<System.Guid> C1CWarehouseID { get; set; }
        public Nullable<System.Guid> C1CDocBuyerOrderID { get; set; }
    
        public virtual C1CContractors C1CContractors { get; set; }
        public virtual C1CContractors C1CConsignees { get; set; }
        public virtual C1CContractors C1CShippers { get; set; }
        public virtual C1CWarehouses C1CWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocShipmentOrderGoods> C1CDocShipmentOrderGoods { get; set; }
    }
}
