//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CDowntimeTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C1CDowntimeTypes()
        {
            this.C1CDowntimeTypeDetails = new HashSet<C1CDowntimeTypeDetails>();
            this.C1CDowntimeTypes1 = new HashSet<C1CDowntimeTypes>();
            this.DocCloseShiftDowntimes = new HashSet<DocCloseShiftDowntimes>();
            this.ProductionTaskDowntimes = new HashSet<ProductionTaskDowntimes>();
            this.DowntimeTemplates = new HashSet<DowntimeTemplates>();
        }
    
        public System.Guid C1CDowntimeTypeID { get; set; }
        public Nullable<bool> IsMetadata { get; set; }
        public Nullable<bool> C1CDeleted { get; set; }
        public Nullable<bool> Folder { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public string C1CCode { get; set; }
        public string Description { get; set; }
        public string FullDescription { get; set; }
        public Nullable<System.Guid> C1CParentID { get; set; }
        public Nullable<System.Guid> C1COEEClassifierID { get; set; }
        public string DowntimeKind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDowntimeTypeDetails> C1CDowntimeTypeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDowntimeTypes> C1CDowntimeTypes1 { get; set; }
        public virtual C1CDowntimeTypes C1CDowntimeTypes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftDowntimes> DocCloseShiftDowntimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionTaskDowntimes> ProductionTaskDowntimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DowntimeTemplates> DowntimeTemplates { get; set; }
    }
}
