//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CDocShipmentOrderGoods
    {
        public System.Guid C1CDocShipmentOrderID { get; set; }
        public int LineNo { get; set; }
        public Nullable<System.Guid> C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public Nullable<System.Guid> C1CMeasureUnitID { get; set; }
        public Nullable<System.Guid> C1CQualityID { get; set; }
        public Nullable<decimal> Coefficient { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> LoadToTop { get; set; }
    
        public virtual C1CDocShipmentOrder C1CDocShipmentOrder { get; set; }
        public virtual C1CMeasureUnits C1CMeasureUnits { get; set; }
        public virtual C1CQuality C1CQuality { get; set; }
    }
}
