//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CPropertyValueGammaPropertyValue
    {
        public System.Guid C1CPropertyValueID { get; set; }
        public System.Guid GammaPropertyID { get; set; }
        public Nullable<decimal> ValueNumeric { get; set; }
    
        public virtual C1CPropertyValues C1CPropertyValues { get; set; }
        public virtual GammaProperties GammaProperties { get; set; }
    }
}
