//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CWarehouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C1CWarehouses()
        {
            this.C1CDocShipmentOrder = new HashSet<C1CDocShipmentOrder>();
            this.C1CDocInternalOrders = new HashSet<C1CDocInternalOrders>();
            this.C1CDocInternalOrders1 = new HashSet<C1CDocInternalOrders>();
            this.C1CDocComplectation = new HashSet<C1CDocComplectation>();
        }
    
        public System.Guid C1CWarehouseID { get; set; }
        public bool IsMetadata { get; set; }
        public bool Marked { get; set; }
        public bool Folder { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string C1CCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> C1CSubdivisionID { get; set; }
        public Nullable<bool> Transportation { get; set; }
        public Nullable<bool> Transit { get; set; }
        public Nullable<bool> ResponsibleStorage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocShipmentOrder> C1CDocShipmentOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocInternalOrders> C1CDocInternalOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocInternalOrders> C1CDocInternalOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CDocComplectation> C1CDocComplectation { get; set; }
    }
}
