//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    
    public partial class CreateUnloadSpools_Result1
    {
        public Nullable<System.Guid> DocID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public string Number { get; set; }
        public string NomenclatureName { get; set; }
    }
}
