//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriticalLogs
    {
        public System.Guid LogID { get; set; }
        public string Log { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogUserID { get; set; }
        public string HostName { get; set; }
        public Nullable<int> LogTypeID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.Guid> DocID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public string TechnicalLog { get; set; }
    }
}
