//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocBrokeProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocBrokeProducts()
        {
            this.DocBrokeProductRejectionReasons = new HashSet<DocBrokeProductRejectionReasons>();
            this.DocRepackProducts = new HashSet<DocRepackProducts>();
        }
    
        public System.Guid DocID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> BrokePlaceID { get; set; }
        public Nullable<byte> BrokeShiftID { get; set; }
        public string BrokePrintName { get; set; }
        public Nullable<System.Guid> C1CRejectionReasonID { get; set; }
        public Nullable<System.Guid> C1CSecondRejectionReasonID { get; set; }
        public string RejectionReasonComment { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<byte> StateID { get; set; }
    
        public virtual DocBroke DocBroke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocBrokeProductRejectionReasons> DocBrokeProductRejectionReasons { get; set; }
        public virtual Places Places { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocRepackProducts> DocRepackProducts { get; set; }
        public virtual C1CRejectionReasons C1CRejectionReasons { get; set; }
        public virtual C1CRejectionReasons C1CRejectionReasons1 { get; set; }
        public virtual Places Places1 { get; set; }
    }
}
