//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocBrokeProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocBrokeProducts()
        {
            this.DocBrokeProductRejectionReasons = new HashSet<DocBrokeProductRejectionReasons>();
        }
    
        public System.Guid DocID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> BrokePlaceID { get; set; }
        public Nullable<byte> BrokeShiftID { get; set; }
        public string BrokePrintName { get; set; }
    
        public virtual DocBroke DocBroke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocBrokeProductRejectionReasons> DocBrokeProductRejectionReasons { get; set; }
        public virtual Places Places { get; set; }
    }
}
