//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocCloseShiftWastes
    {
        public System.Guid DocCloseWhiftWasteID { get; set; }
        public System.Guid DocID { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public decimal Quantity { get; set; }
        public System.Guid C1CMeasureUnitID { get; set; }
    
        public virtual C1CCharacteristics C1CCharacteristics { get; set; }
        public virtual C1CMeasureUnits C1CMeasureUnits { get; set; }
        public virtual Docs Docs { get; set; }
        public virtual C1CNomenclature C1CNomenclature { get; set; }
    }
}
