//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocComplectation
    {
        public System.Guid DocComplectationID { get; set; }
        public Nullable<System.Guid> DocProductionID { get; set; }
        public Nullable<System.Guid> DocWithdrawalID { get; set; }
        public System.Guid C1CDocComplectationID { get; set; }
    
        public virtual DocProduction DocProduction { get; set; }
        public virtual Docs Docs { get; set; }
        public virtual DocWithdrawal DocWithdrawal { get; set; }
        public virtual C1CDocComplectation C1CDocComplectation { get; set; }
    }
}
