//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocCloseShiftRemainders
    {
        public System.Guid DocCloseShiftRemainderID { get; set; }
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<bool> IsSourceProduct { get; set; }
        public Nullable<System.Guid> DocWithdrawalID { get; set; }
    
        public virtual Docs DocWithdrawals { get; set; }
        public virtual Docs DocCloseShifts { get; set; }
    }
}
