//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocInventarisationProducts
    {
        public System.Guid DocID { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
    
        public virtual Docs Docs { get; set; }
        public virtual Products Products { get; set; }
    }
}
