//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocMaterialTanks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocMaterialTanks()
        {
            this.DocMaterialTankRemainders = new HashSet<DocMaterialTankRemainders>();
        }
    
        public int DocMaterialTankID { get; set; }
        public string Name { get; set; }
        public int DocMaterialTankGroupID { get; set; }
        public int Volume { get; set; }
    
        public virtual DocMaterialTankGroups DocMaterialTankGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocMaterialTankRemainders> DocMaterialTankRemainders { get; set; }
    }
}
