//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocRepack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocRepack()
        {
            this.DocRepackProducts = new HashSet<DocRepackProducts>();
        }
    
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
    
        public virtual Docs Docs { get; set; }
        public virtual ProductionTasks ProductionTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocRepackProducts> DocRepackProducts { get; set; }
    }
}
