//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Docs()
        {
            this.DocChangeStateProducts = new HashSet<DocChangeStateProducts>();
            this.DocProducts = new HashSet<DocProducts>();
            this.DocWithdrawalMaterials = new HashSet<DocWithdrawalMaterials>();
            this.DocCloseShiftDocs = new HashSet<Docs>();
            this.DocCloseShift = new HashSet<Docs>();
            this.DocCloseShiftWithdrawals = new HashSet<DocWithdrawal>();
            this.DocUnpackWithdrawals = new HashSet<DocWithdrawal>();
            this.DocCloseShiftRemainders2 = new HashSet<DocCloseShiftRemainders>();
            this.DocCloseShiftRemainders = new HashSet<DocCloseShiftRemainders>();
            this.DocCloseShiftProducts = new HashSet<Products>();
            this.DocInventarisationProducts = new HashSet<DocInventarisationProducts>();
            this.DocCloseShiftNomenclatureRests = new HashSet<DocCloseShiftNomenclatureRests>();
            this.DocCloseShiftWastes = new HashSet<DocCloseShiftWastes>();
            this.DocCloseShiftSamples = new HashSet<DocCloseShiftSamples>();
            this.DocCloseShiftMaterials = new HashSet<DocCloseShiftMaterials>();
            this.DocCloseShiftMovementProducts = new HashSet<DocCloseShiftMovementProducts>();
            this.DocCloseShiftUtilizationProducts = new HashSet<DocCloseShiftUtilizationProducts>();
            this.DocCloseShiftRepackProducts = new HashSet<DocCloseShiftRepackProducts>();
        }
    
        public System.Guid DocID { get; set; }
        public Nullable<bool> IsMarked { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Number { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string PrintName { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsFromOldGamma { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<System.Guid> PersonGuid { get; set; }
        public Nullable<int> PersonID { get; set; }
    
        public virtual DocBroke DocBroke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocChangeStateProducts> DocChangeStateProducts { get; set; }
        public virtual DocMovement DocMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocProducts> DocProducts { get; set; }
        public virtual DocTypes DocTypes { get; set; }
        public virtual DocWithdrawal DocWithdrawal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocWithdrawalMaterials> DocWithdrawalMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docs> DocCloseShiftDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docs> DocCloseShift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocWithdrawal> DocCloseShiftWithdrawals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocWithdrawal> DocUnpackWithdrawals { get; set; }
        public virtual DocProduction DocProduction { get; set; }
        public virtual Places Places { get; set; }
        public virtual DocMovementOrder DocMovementOrder { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftRemainders> DocCloseShiftRemainders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftRemainders> DocCloseShiftRemainders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> DocCloseShiftProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocInventarisationProducts> DocInventarisationProducts { get; set; }
        public virtual Persons Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftNomenclatureRests> DocCloseShiftNomenclatureRests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftWastes> DocCloseShiftWastes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftSamples> DocCloseShiftSamples { get; set; }
        public virtual DocComplectation DocComplectation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftMaterials> DocCloseShiftMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftMovementProducts> DocCloseShiftMovementProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftUtilizationProducts> DocCloseShiftUtilizationProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocCloseShiftRepackProducts> DocCloseShiftRepackProducts { get; set; }
    }
}
