//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    
    public partial class FillDocCloseShiftRwSpools_Result3
    {
        public System.Guid ProductID { get; set; }
        public System.Guid C1CCharacteristicID { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public string NomenclatureName { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Number { get; set; }
        public System.Guid DocID { get; set; }
    }
}
