//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    
    public partial class GetMaterialNomenclatureFolders_Result1
    {
        public System.Guid FolderID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
    }
}
