//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenclatureGammaInfo
    {
        public System.Guid C1CNomenclatureID { get; set; }
        public string TextPTM { get; set; }
    
        public virtual C1CNomenclature C1CNomenclature { get; set; }
    }
}
