//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.DocInProducts = new HashSet<DocInProducts>();
            this.DocOutProducts = new HashSet<DocOutProducts>();
            this.DocShipmentOrders = new HashSet<DocShipmentOrders>();
            this.DocShipmentOrders1 = new HashSet<DocShipmentOrders>();
            this.Docs = new HashSet<Docs>();
        }
    
        public System.Guid PersonID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> PostTypeID { get; set; }
        public string Name { get; set; }
        public string Barcode { get; set; }
        public string Password { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        public virtual Branches Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocInProducts> DocInProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocOutProducts> DocOutProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocShipmentOrders> DocShipmentOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocShipmentOrders> DocShipmentOrders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docs> Docs { get; set; }
        public virtual PostTypes PostTypes { get; set; }
        public virtual Places Places { get; set; }
        public virtual Users Users { get; set; }
    }
}
