//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTaskBatches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionTaskBatches()
        {
            this.ProductionTasks = new HashSet<ProductionTasks>();
        }
    
        public System.Guid ProductionTaskBatchID { get; set; }
        public short BatchKindID { get; set; }
        public byte ProductionTaskStateID { get; set; }
        public Nullable<System.Guid> C1CContractorID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
        public Nullable<short> ProcessModelID { get; set; }
        public Nullable<bool> PartyControl { get; set; }
    
        public virtual C1CContractors C1CContractors { get; set; }
        public virtual ProcessModels ProcessModels { get; set; }
        public virtual ProductionTaskStates ProductionTaskStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionTasks> ProductionTasks { get; set; }
    }
}
