//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotProduct1CCharacteristic
    {
        public int ProdNumber { get; set; }
        public string C1CCharCode { get; set; }
        public Nullable<System.DateTime> DateInsertToRobot { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public Nullable<System.Guid> C1CNomenclatureID { get; set; }
    }
}
