//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermits
    {
        public System.Guid RoleID { get; set; }
        public System.Guid PermitID { get; set; }
        public byte Mark { get; set; }
    
        public virtual Permits Permits { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
