//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceSpools
    {
        public int PlaceID { get; set; }
        public Nullable<System.Guid> Unwinder1Spool { get; set; }
        public Nullable<bool> Unwinder1Active { get; set; }
        public Nullable<System.Guid> Unwinder2Spool { get; set; }
        public Nullable<bool> Unwinder2Active { get; set; }
        public Nullable<System.Guid> Unwinder3Spool { get; set; }
        public Nullable<bool> Unwinder3Active { get; set; }
    
        public virtual ProductSpools ProductSpools { get; set; }
        public virtual ProductSpools ProductSpools1 { get; set; }
        public virtual ProductSpools ProductSpools2 { get; set; }
        public virtual Places Places { get; set; }
    }
}
