//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpoolInstallLog
    {
        public System.Guid SpoolInstallLogID { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> UnwinderID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Places Places { get; set; }
    }
}
