//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.CurrentPlaceUsers = new HashSet<CurrentPlaceUsers>();
            this.Docs = new HashSet<Docs>();
            this.UserPrintNames = new HashSet<UserPrintNames>();
            this.Places = new HashSet<Places>();
            this.LogEvents = new HashSet<LogEvents>();
        }
    
        public System.Guid UserID { get; set; }
        public System.Guid RoleID { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
        public Nullable<int> PostTypeID { get; set; }
        public Nullable<System.DateTime> PassChange { get; set; }
        public Nullable<bool> PassMustChange { get; set; }
        public bool Exports { get; set; }
        public bool DBAdmin { get; set; }
        public Nullable<bool> ProgramAdmin { get; set; }
        public byte ShiftID { get; set; }
        public Nullable<bool> MobileComputer { get; set; }
        public Nullable<short> DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentPlaceUsers> CurrentPlaceUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docs> Docs { get; set; }
        public virtual PostTypes PostTypes { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPrintNames> UserPrintNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Places> Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogEvents> LogEvents { get; set; }
        public virtual Departments Departments { get; set; }
    }
}
