//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPrintNames
    {
        public System.Guid UserPrintNameID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string PrintName { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
