//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v1CDocComplectationPositions
    {
        public System.Guid C1CDocComplectationID { get; set; }
        public string Nomenclature { get; set; }
        public string OldCharacteristic { get; set; }
        public string NewCharacteristic { get; set; }
        public Nullable<decimal> DocQuantity { get; set; }
        public Nullable<decimal> Withdraw { get; set; }
        public Nullable<decimal> Complected { get; set; }
    }
}
