//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v1CWorkingSpecifications
    {
        public System.DateTime Period { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public Nullable<System.Guid> C1CPlaceID { get; set; }
        public System.Guid C1CSpecificationID { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public string C1CCode { get; set; }
    }
}
