//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDocMovementGoods
    {
        public System.Guid DocMovementID { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public System.Guid C1CCharacteristicID { get; set; }
        public string NomenclatureName { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> InQuantity { get; set; }
        public Nullable<System.Guid> C1CQualityID { get; set; }
        public Nullable<decimal> AcceptedQuantity { get; set; }
    }
}
