//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDocRepackProducts
    {
        public System.Guid DocRepackProductID { get; set; }
        public System.Guid DocRepackID { get; set; }
        public string DocRepackNumber { get; set; }
        public System.DateTime DocRepackDate { get; set; }
        public bool DocRepackIsConfirmed { get; set; }
        public System.Guid ProductID { get; set; }
        public string ProductNumber { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public Nullable<System.Guid> C1CMeasureUnitID { get; set; }
        public string MeasureUnitName { get; set; }
        public string NomenclatureName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityGood { get; set; }
        public Nullable<decimal> QuantityBroke { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public byte ProductKindID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
        public Nullable<System.Guid> DocBrokeID { get; set; }
        public string DocBrokeNumber { get; set; }
        public Nullable<System.DateTime> DocBrokeDate { get; set; }
    }
}
