//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGroupPackSpools
    {
        public System.Guid ProductGroupPackID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
    }
}
