//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNomenclatureSGBProperties
    {
        public System.Guid C1CNomenclatureID { get; set; }
        public string Kind { get; set; }
        public string BasisWeight { get; set; }
        public Nullable<decimal> BasisWeightNumeric { get; set; }
        public string ColorGroup { get; set; }
        public string Composition { get; set; }
        public string Purpose { get; set; }
        public string RawMaterial { get; set; }
        public string SortValue { get; set; }
        public string LayerNumber { get; set; }
        public Nullable<int> LayerNumberNumeric { get; set; }
        public string CodeComposition { get; set; }
    }
}
