//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPlacePropertiesValues
    {
        public int PlaceID { get; set; }
        public string Place { get; set; }
        public Nullable<decimal> Format { get; set; }
        public Nullable<decimal> CoreDiameter { get; set; }
    }
}
