//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPMSpoolsToGroupPack
    {
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> ProductGroupPackID { get; set; }
        public System.DateTime PMDate { get; set; }
        public Nullable<byte> ShiftId { get; set; }
        public string NomenclatureName { get; set; }
        public string PMNumber { get; set; }
        public string WrNumber { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public System.Guid C1CCharacteristicID { get; set; }
    }
}
