//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductsInfo
    {
        public System.Guid DocID { get; set; }
        public System.Guid ProductID { get; set; }
        public byte ProductKindID { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string BarCode { get; set; }
        public string PrintName { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string BaseMeasureUnit { get; set; }
        public Nullable<decimal> BaseMeasureUnitQuantity { get; set; }
        public decimal ProductionQuantity { get; set; }
        public Nullable<decimal> GrossQuantity { get; set; }
        public Nullable<decimal> BaseMeasureUnitGrossQuantity { get; set; }
        public string NomenclatureName { get; set; }
        public string ShortNomenclatureName { get; set; }
        public Nullable<byte> NomenclatureKindID { get; set; }
        public string Place { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public short PlaceGroupID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public byte StateID { get; set; }
        public Nullable<decimal> ChangeStateQuantity { get; set; }
        public Nullable<System.Guid> C1CQualityID { get; set; }
        public string RejectionReason { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<bool> IsWrittenOff { get; set; }
        public string State { get; set; }
        public Nullable<System.Guid> BaseMeasureUnitID { get; set; }
        public Nullable<int> CurrentPlaceID { get; set; }
        public Nullable<System.Guid> CurrentPlaceZoneID { get; set; }
        public string CurrentPlace { get; set; }
        public int GroupNumberByTimeProductionDate { get; set; }
        public string SCU { get; set; }
        public Nullable<System.Guid> KindValueID { get; set; }
        public string KindValue { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
        public string ProductionTaskNumber { get; set; }
    }
}
