//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductsCurrentStateInfo
    {
        public System.Guid ProductID { get; set; }
        public byte StateID { get; set; }
        public Nullable<System.Guid> C1CQualityID { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<decimal> ChangeStateQuantity { get; set; }
        public Nullable<bool> IsWrittenOff { get; set; }
        public string State { get; set; }
    }
}
