//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRobotNomenclatures
    {
        public int ProdNumber { get; set; }
        public string ProdDescription { get; set; }
        public string EANFullPallet { get; set; }
        public int ProductionLine { get; set; }
        public int PlaceID { get; set; }
        public string ProdName { get; set; }
    }
}
