//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double FindProductionTaskHeight {
            get {
                return ((double)(this["FindProductionTaskHeight"]));
            }
            set {
                this["FindProductionTaskHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double FindProductionTaskWidth {
            get {
                return ((double)(this["FindProductionTaskWidth"]));
            }
            set {
                this["FindProductionTaskWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FindProductionTaskLeft {
            get {
                return ((double)(this["FindProductionTaskLeft"]));
            }
            set {
                this["FindProductionTaskLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double FindProductionTaskTop {
            get {
                return ((double)(this["FindProductionTaskTop"]));
            }
            set {
                this["FindProductionTaskTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double DocCloseShiftsHeight {
            get {
                return ((double)(this["DocCloseShiftsHeight"]));
            }
            set {
                this["DocCloseShiftsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double DocCloseShiftsWidth {
            get {
                return ((double)(this["DocCloseShiftsWidth"]));
            }
            set {
                this["DocCloseShiftsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double DocCloseShiftsLeft {
            get {
                return ((double)(this["DocCloseShiftsLeft"]));
            }
            set {
                this["DocCloseShiftsLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double DocCloseShiftsTop {
            get {
                return ((double)(this["DocCloseShiftsTop"]));
            }
            set {
                this["DocCloseShiftsTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double ProductionTaskBatchHeight {
            get {
                return ((double)(this["ProductionTaskBatchHeight"]));
            }
            set {
                this["ProductionTaskBatchHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double ProductionTaskBatchWidth {
            get {
                return ((double)(this["ProductionTaskBatchWidth"]));
            }
            set {
                this["ProductionTaskBatchWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double ProductionTaskBatchLeft {
            get {
                return ((double)(this["ProductionTaskBatchLeft"]));
            }
            set {
                this["ProductionTaskBatchLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double ProductionTaskBatchTop {
            get {
                return ((double)(this["ProductionTaskBatchTop"]));
            }
            set {
                this["ProductionTaskBatchTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double DocProductHeight {
            get {
                return ((double)(this["DocProductHeight"]));
            }
            set {
                this["DocProductHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double DocProductWidth {
            get {
                return ((double)(this["DocProductWidth"]));
            }
            set {
                this["DocProductWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double DocProductLeft {
            get {
                return ((double)(this["DocProductLeft"]));
            }
            set {
                this["DocProductLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double DocProductTop {
            get {
                return ((double)(this["DocProductTop"]));
            }
            set {
                this["DocProductTop"] = value;
            }
        }
    }
}
