//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CEnumGroupTypes
    {
        public C1CEnumGroupTypes()
        {
            this.C1CNomenclatureGroups = new HashSet<C1CNomenclatureGroups>();
        }
    
        public int C1CEnumGroupTypeID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
    
        public virtual ICollection<C1CNomenclatureGroups> C1CNomenclatureGroups { get; set; }
    }
}
