//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CEnumGroupTypes
    {
        public C1CEnumGroupTypes()
        {
            this.C1CNomenclatureGroups = new HashSet<C1CNomenclatureGroups>();
        }
    
        public int C1CEnumGroupTypeID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
    
        public virtual ICollection<C1CNomenclatureGroups> C1CNomenclatureGroups { get; set; }
    }
}
