//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CNomenclatureGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C1CNomenclatureGroups()
        {
            this.C1CNomenclature = new HashSet<C1CNomenclature>();
        }
    
        public System.Guid C1CNomenclatureGroupID { get; set; }
        public string C1CCode { get; set; }
        public Nullable<int> C1CEnumGroupTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> C1CMeasureUnitID { get; set; }
    
        public virtual C1CEnumGroupTypes C1CEnumGroupTypes { get; set; }
        public virtual C1CMeasureUnits C1CMeasureUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1CNomenclature> C1CNomenclature { get; set; }
    }
}
