//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CNomenclatureProperties
    {
        public System.Guid C1CNomenclatureID { get; set; }
        public System.Guid C1CPropertyID { get; set; }
        public Nullable<System.Guid> C1CPropertyValueID { get; set; }
        public string ValueText { get; set; }
        public Nullable<decimal> ValueNumeric { get; set; }
    
        public virtual C1CProperties C1CProperties { get; set; }
        public virtual C1CPropertyValues C1CPropertyValues { get; set; }
        public virtual C1CNomenclature C1CNomenclature { get; set; }
    }
}
