//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CPropertyValueGammaPropertyValue
    {
        public System.Guid C1CPropertyValueID { get; set; }
        public System.Guid GammaPropertyID { get; set; }
        public Nullable<decimal> ValueNumeric { get; set; }
    
        public virtual C1CPropertyValues C1CPropertyValues { get; set; }
        public virtual GammaProperties GammaProperties { get; set; }
    }
}
