//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CRejectionReasons
    {
        public C1CRejectionReasons()
        {
            this.DocProductChangeState = new HashSet<DocProductChangeState>();
        }
    
        public System.Guid C1CRejectionReasonID { get; set; }
        public Nullable<bool> IsMarked { get; set; }
        public Nullable<bool> IsFolder { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Description { get; set; }
        public string FullDescription { get; set; }
    
        public virtual ICollection<DocProductChangeState> DocProductChangeState { get; set; }
    }
}
