//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1CRejectionReasons
    {
        public C1CRejectionReasons()
        {
            this.DocChangeStateProducts = new HashSet<DocChangeStateProducts>();
        }
    
        public System.Guid C1CRejectionReasonID { get; set; }
        public Nullable<bool> IsMarked { get; set; }
        public Nullable<bool> IsFolder { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Description { get; set; }
        public string FullDescription { get; set; }
    
        public virtual ICollection<DocChangeStateProducts> DocChangeStateProducts { get; set; }
    }
}
