//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocChangeStateProducts
    {
        public System.Guid DocID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public byte StateID { get; set; }
        public Nullable<System.Guid> C1CRejectionReasonID { get; set; }
    
        public virtual C1CRejectionReasons C1CRejectionReasons { get; set; }
        public virtual Docs Docs { get; set; }
        public virtual ProductStates ProductStates { get; set; }
    }
}
