//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocMovement
    {
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> InPlaceID { get; set; }
        public Nullable<System.Guid> OutPlaceID { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Places Places1 { get; set; }
        public virtual Docs Docs { get; set; }
    }
}
