//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocMovement
    {
        public System.Guid DocID { get; set; }
        public Nullable<int> InPlaceID { get; set; }
        public Nullable<int> OutPlaceID { get; set; }
    
        public virtual Docs Docs { get; set; }
        public virtual Places Places { get; set; }
        public virtual Places Places1 { get; set; }
    }
}
