//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocMovementOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocMovementOrder()
        {
            this.DocMovementOrderNomenclature = new HashSet<DocMovementOrderNomenclature>();
        }
    
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> C1CDocID { get; set; }
        public Nullable<int> OutPlaceID { get; set; }
        public Nullable<int> InPlaceID { get; set; }
    
        public virtual Docs Docs { get; set; }
        public virtual Places PlacesFrom { get; set; }
        public virtual Places PlacesTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocMovementOrderNomenclature> DocMovementOrderNomenclature { get; set; }
    }
}
