//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocOutProducts
    {
        public System.Guid DocID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> PlaceZoneID { get; set; }
        public Nullable<System.Guid> PlaceZoneCellID { get; set; }
        public Nullable<System.Guid> PersonID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual PlaceZoneCells PlaceZoneCells { get; set; }
        public virtual PlaceZones PlaceZones { get; set; }
        public virtual Products Products { get; set; }
        public virtual DocMovement DocMovement { get; set; }
    }
}
