//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocProductChangeState
    {
        public System.Guid DocID { get; set; }
        public byte StateID { get; set; }
        public Nullable<System.Guid> C1CRejectionReasonID { get; set; }
    
        public virtual C1CRejectionReasons C1CRejectionReasons { get; set; }
        public virtual Docs Docs { get; set; }
    }
}
