//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocShipmentOrderInfo
    {
        public System.Guid C1CDocShipmentOrderID { get; set; }
        public Nullable<int> ActivePersonID { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<bool> IsShipped { get; set; }
    
        public virtual C1CDocShipmentOrder C1CDocShipmentOrder { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
