//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocShipment
    {
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> ActiveUserID { get; set; }
        public Nullable<System.Guid> C1CDocOrderID { get; set; }
    
        public virtual Docs Docs { get; set; }
        public virtual Users Users { get; set; }
    }
}
