//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docs
    {
        public Docs()
        {
            this.DocProducts = new HashSet<DocProducts>();
        }
    
        public System.Guid DocID { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Number { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
    
        public virtual DocMovement DocMovement { get; set; }
        public virtual DocProduction DocProduction { get; set; }
        public virtual ICollection<DocProducts> DocProducts { get; set; }
        public virtual DocWithdrawal DocWithdrawal { get; set; }
        public virtual Users Users { get; set; }
    }
}
