//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocWithdrawal
    {
        public DocWithdrawal()
        {
            this.DocProduction = new HashSet<DocProduction>();
        }
    
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> OutPlaceID { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual ICollection<DocProduction> DocProduction { get; set; }
        public virtual Docs Docs { get; set; }
    }
}
