//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    
    public partial class FindNomenclatureByStringWithFilter_Result1
    {
        public System.Guid C1CNomenclatureID { get; set; }
        public string Name { get; set; }
    }
}
