//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GammaProperties
    {
        public GammaProperties()
        {
            this.C1CPropertyValueGammaPropertyValue = new HashSet<C1CPropertyValueGammaPropertyValue>();
            this.C1CProperties = new HashSet<C1CProperties>();
        }
    
        public System.Guid GammaPropertyID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<C1CPropertyValueGammaPropertyValue> C1CPropertyValueGammaPropertyValue { get; set; }
        public virtual ICollection<C1CProperties> C1CProperties { get; set; }
    }
}
