//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permits
    {
        public Permits()
        {
            this.PermitTables = new HashSet<PermitTables>();
            this.RolePermits = new HashSet<RolePermits>();
        }
    
        public System.Guid PermitID { get; set; }
        public Nullable<byte> GroupNumber { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PermitTables> PermitTables { get; set; }
        public virtual ICollection<RolePermits> RolePermits { get; set; }
    }
}
