//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitTables
    {
        public System.Guid PermitTableID { get; set; }
        public System.Guid PermitID { get; set; }
        public string Name { get; set; }
        public string Columns { get; set; }
    
        public virtual Permits Permits { get; set; }
    }
}
