//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public Places()
        {
            this.DocMovement = new HashSet<DocMovement>();
            this.DocMovement1 = new HashSet<DocMovement>();
            this.DocProduction = new HashSet<DocProduction>();
            this.Docs = new HashSet<Docs>();
            this.DocWithdrawal = new HashSet<DocWithdrawal>();
            this.Rests = new HashSet<Rests>();
            this.ProductionTasks = new HashSet<ProductionTasks>();
            this.Users = new HashSet<Users>();
        }
    
        public int PlaceID { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public short DepartmentID { get; set; }
        public Nullable<short> PlaceGroupID { get; set; }
        public Nullable<bool> IsProductionPlace { get; set; }
        public Nullable<bool> IsWarehouse { get; set; }
        public Nullable<System.Guid> C1CPlaceID { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual ICollection<DocMovement> DocMovement { get; set; }
        public virtual ICollection<DocMovement> DocMovement1 { get; set; }
        public virtual ICollection<DocProduction> DocProduction { get; set; }
        public virtual ICollection<Docs> Docs { get; set; }
        public virtual ICollection<DocWithdrawal> DocWithdrawal { get; set; }
        public virtual ICollection<Rests> Rests { get; set; }
        public virtual SourceSpools SourceSpools { get; set; }
        public virtual PlaceGroups PlaceGroups { get; set; }
        public virtual ICollection<ProductionTasks> ProductionTasks { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
