//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceGroups
    {
        public PlaceGroups()
        {
            this.Places = new HashSet<Places>();
            this.C1CNomenclature = new HashSet<C1CNomenclature>();
        }
    
        public short PlaceGroupID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Places> Places { get; set; }
        public virtual ICollection<C1CNomenclature> C1CNomenclature { get; set; }
    }
}
