//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTaskSGB
    {
        public System.Guid ProductionTaskID { get; set; }
        public Nullable<int> Diameter { get; set; }
        public Nullable<int> DiameterPlus { get; set; }
        public Nullable<int> DiameterMinus { get; set; }
        public Nullable<int> Crepe { get; set; }
    
        public virtual ProductionTasks ProductionTasks { get; set; }
    }
}
