//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTasks
    {
        public ProductionTasks()
        {
            this.ProductionTaskRWCutting = new HashSet<ProductionTaskRWCutting>();
        }
    
        public System.Guid ProductionTaskID { get; set; }
        public Nullable<short> ProductionTaskKindID { get; set; }
        public System.Guid PlaceID { get; set; }
        public Nullable<byte> ProductionTaskStateID { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsInPlan { get; set; }
    
        public virtual C1CCharacteristics C1CCharacteristics { get; set; }
        public virtual C1CNomenclature C1CNomenclature { get; set; }
        public virtual Places Places { get; set; }
        public virtual ICollection<ProductionTaskRWCutting> ProductionTaskRWCutting { get; set; }
    }
}
