//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTaskConfig
    {
        public System.Guid ProductionTaskConfigID { get; set; }
        public System.Guid ProductionTaskID { get; set; }
        public System.Guid C1CNomenclatureID { get; set; }
        public System.Guid C1CCharacteristicID { get; set; }
        public Nullable<byte> DocProductsQuantity { get; set; }
        public int TaskQuantity { get; set; }
    
        public virtual C1CCharacteristics C1CCharacteristics { get; set; }
        public virtual C1CNomenclature C1CNomenclature { get; set; }
        public virtual ProductionTasks ProductionTasks { get; set; }
    }
}
