//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.DocProducts = new HashSet<DocProducts>();
            this.SpoolInstallLog = new HashSet<SpoolInstallLog>();
        }
    
        public System.Guid ProductID { get; set; }
        public string Number { get; set; }
        public string BarCode { get; set; }
        public Nullable<byte> ProductKindID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocProducts> DocProducts { get; set; }
        public virtual ProductGroupPacks ProductGroupPacks { get; set; }
        public virtual ProductKinds ProductKinds { get; set; }
        public virtual ProductPallets ProductPallets { get; set; }
        public virtual Rests Rests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpoolInstallLog> SpoolInstallLog { get; set; }
        public virtual ProductSpools ProductSpools { get; set; }
    }
}
