//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPallets
    {
        public ProductPallets()
        {
            this.ProductPalletItems = new HashSet<ProductPalletItems>();
        }
    
        public System.Guid ProductID { get; set; }
    
        public virtual ICollection<ProductPalletItems> ProductPalletItems { get; set; }
        public virtual Products Products { get; set; }
    }
}
