//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTaskStates
    {
        public ProductionTaskStates()
        {
            this.ProductionTaskBatches = new HashSet<ProductionTaskBatches>();
        }
    
        public byte ProductionTaskStateID { get; set; }
        public string Name { get; set; }
        public bool IsActual { get; set; }
    
        public virtual ICollection<ProductionTaskBatches> ProductionTaskBatches { get; set; }
    }
}
