//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStates
    {
        public ProductStates()
        {
            this.DocChangeStateProducts = new HashSet<DocChangeStateProducts>();
        }
    
        public byte StateID { get; set; }
        public Nullable<System.Guid> C1CQualityID { get; set; }
        public string Name { get; set; }
    
        public virtual C1CQuality C1CQuality { get; set; }
        public virtual ICollection<DocChangeStateProducts> DocChangeStateProducts { get; set; }
    }
}
