//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public Reports()
        {
            this.Templates = new HashSet<Templates>();
        }
    
        public System.Guid ReportID { get; set; }
        public string Name { get; set; }
        public bool IsReport { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
    
        public virtual ICollection<Templates> Templates { get; set; }
    }
}
