//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.RolePermits = new HashSet<RolePermits>();
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid RoleID { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<RolePermits> RolePermits { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
