//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermits
    {
        public System.Guid RoleID { get; set; }
        public System.Guid PermitID { get; set; }
        public byte Mark { get; set; }
    
        public virtual Permits Permits { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
