//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceSpools
    {
        public System.Guid PlaceID { get; set; }
        public Nullable<System.Guid> Unwinder1Spool { get; set; }
        public Nullable<bool> Unwinder1Active { get; set; }
        public Nullable<System.Guid> Unwinder2Spool { get; set; }
        public Nullable<bool> Unwinder2Active { get; set; }
        public Nullable<System.Guid> Unwinder3Spool { get; set; }
        public Nullable<bool> Unwinder3Active { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual ProductSpools ProductSpools { get; set; }
        public virtual ProductSpools ProductSpools1 { get; set; }
        public virtual ProductSpools ProductSpools2 { get; set; }
    }
}
