//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Docs = new HashSet<Docs>();
            this.ProductionTaskBatches = new HashSet<ProductionTaskBatches>();
        }
    
        public System.Guid UserID { get; set; }
        public System.Guid RoleID { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
        public Nullable<System.DateTime> PassChange { get; set; }
        public Nullable<bool> PassMustChange { get; set; }
        public int PlaceID { get; set; }
        public bool Exports { get; set; }
        public bool DBAdmin { get; set; }
        public byte ShiftID { get; set; }
        public Nullable<bool> ProgramAdmin { get; set; }
    
        public virtual ICollection<Docs> Docs { get; set; }
        public virtual Places Places { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<ProductionTaskBatches> ProductionTaskBatches { get; set; }
    }
}
