//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductsInfo
    {
        public System.Guid DocID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<byte> ProductKindID { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string BarCode { get; set; }
        public Nullable<System.Guid> C1CNomenclatureID { get; set; }
        public Nullable<System.Guid> C1CCharacteristicID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string NomenclatureName { get; set; }
        public string Place { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public byte StateID { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsWrittenOff { get; set; }
        public string State { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string RejectionReason { get; set; }
    }
}
