//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductionTaskProducts
    {
        public Nullable<System.Guid> ProductionTaskID { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public System.Guid DocID { get; set; }
        public Nullable<byte> ProductKindID { get; set; }
        public System.Guid ProductID { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string NomenclatureName { get; set; }
        public Nullable<System.Guid> NomenclatureID { get; set; }
        public Nullable<System.Guid> CharacteristicID { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
